### ISSUE TITLE
Crash on Bitwig Studio when modulating with MPE

### ISSUE THREAD

**Issue by mobiuscog** [surge-synthesizer/clap-saw-demo#13]
The attached Bitwig project (with self-built plugin included) is crashing, reproducibly.

It seems to be when a parameter is being modulated at a high rate. Removing the modulation removes the crash, as does removing the MPE note expression (or slightly changing it) in the example. 

It **may** be a bitwig/CLAP problem as the same also happens in Surge XT CLAP, but not in Surge XT VST

[crash1.zip](https://github.com/surge-synthesizer/clap-saw-demo/files/8933917/crash1.zip)

**Comment by baconpaul** [comment]
ahh i see the problem i think
it just keeps stacking LFOs
I wonder why
This may be a bitwig bug with modulator lifetime indeed
which bitwig version were you using?

**Comment by mobiuscog** [comment]
The latest beta - 4.3 Beta 7

**Comment by baconpaul** [comment]
thanks

**Comment by baconpaul** [comment]
by the way it doesn't crash on mac, but i seem to get loads of dots on the lfo.

**Comment by baconpaul** [comment]
So @mobiuscog this is definitely a bitwig bug. When I open your system i start getting a bunch of modulation messages targets at me in monophonic form which are not smooth

but also i applied those to inactive voices which i think may crash. That "shouldn't" happen but i put in a check now to make sure it doesn't so pull clap-saw-demo and you may get a non-crashing but still-broken session

I've reported the problem over to alex and i'll leave this open until we figure out what makes this project screwy

Thanks!

**Comment by mobiuscog** [comment]
I've done more testing this morning @baconpaul and I believe it's definitely a Bitwig/CLAP issue.
From testing different variables, it seems that even just adding the LFO will crash the engine, even if it's not connected to any parameters - if poly/per-voice is enabled, the crash no longer occurs.

It does also seem related to something specific about the section of notes/MPE as it doesn't happen on just anything, but I can't pin that down.

Let me know if I should report this to Bitwig instead, or if you have a direct link feel free to point them in my direction. I'm happy for this to be closed with respect to the demo project.

**Comment by baconpaul** [comment]
Ok let’s put the info https://github.com/free-audio/interop-tracker/issues/27 which is the clap dev interop bug tracker. Will leave this open but I agree it’s not the saw
