### ISSUE TITLE
VSTGUI not cleanly exiting on Windows on plugin deletion

### ISSUE THREAD

**Issue by mobiuscog** [surge-synthesizer/clap-saw-demo#17]
Recently, I've noticed that on removing the plugin (or closing Bitwig) on Windows an exception is often thrown:
![oops](https://user-images.githubusercontent.com/1312115/174493075-232adf28-0aa0-4504-bd11-d1f3e4124332.png)

I tried to debug into the stack, and the exception is being thrown by the assert here:
https://github.com/steinbergmedia/vstgui/blob/addf12b9486fd9460a3abf2cf2a2dd96c44ed807/vstgui/lib/platform/win32/win32directcomposition.cpp#L647

I presume this means that something has not been cleared that is expected, but I'm not knowledgeable enough on VSTGUI to have much more insight. I went back to the revision before the couple of PRs I recently made, and it still has the same problem, so it's not new - I just didn't notice it previously (it sometimes seems to popup in the background and briefly show on the taskbar).

**Comment by baconpaul** [comment]
on well darnit cleanup is hard
there's a call to VSTGUI::Exit in a finally inside clap-saw-demo-editor - for now just comment that out on windows i bet

**Comment by mobiuscog** [comment]
Seems fixed with my other changes in #19
