### ISSUE TITLE
Bitwig doesn't recognize the built clap file

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [surge-synthesizer/clap-saw-demo#33]
I'm not sure if I'm doing something wrong here.

When I build this .clap file and try point bitwig to the `ignore/build` folder, it doesn't add this saw demo to my list of plugins. As far as I can tell, there doesn't seem to be any build errors. I'm using Bitwig 4.3. I've built this package on an arch-linux based system. When I check the plugin loading log in bitwig, it prints out the following message:

```
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load CLAP plug-in /home/eoin/Source/clap-saw-demo/ignore/build/clap-saw-demo.clap: /home/eoin/Source/clap-saw-demo/ignore/build/clap-saw-demo.clap: undefined symbol: _ZNK4clap7helpers9HostProxyILNS0_19MisbehaviourHandlerE1ELNS0_13CheckingLevelE2EE20canUsePosixFdSupportEv
```

Any ideas?

**Comment by baconpaul** [comment]
Huh wow that is odd. I’ve mostly tested in mac recently but I don’t know why that symbol would be missing. 

It is almost definitely e40d382465abda1ebc131e087e5b55102ec3c4f0 that commit 

I don’t have a Linux box available today but will tomorrow. But if you would like to

1. can you try building the commit prior to that? 
2. if that works then it is a template instantiating problem. I bet that editor file needs an inckude host-proxy.hxx if Linux at the top 
3. If 2 is the fix and toh try it and it works and you want to send a pr that would be appreciated 

and if not I can look later this week!

thanks

**Comment by Eoin-ONeill-Yokai** [comment]
That correction seemed to work. @baconpaul Thanks!

**Comment by baconpaul** [comment]
Great. I will merge it this morning.

I don't know why it isn't a problem here on ubuntu 20 but let me get it merged. 

Do you mind sharing what toolchain you are using to build?

**Comment by baconpaul** [comment]
OK thanks for flagging this. I just merged a change which works on ubuntu 20 still and contains what I think is the fix for your toolchain also. Also upgrades to clap 1.1.1 and adds the build time and date on the UI.
