### ISSUE TITLE
 other.invoke (false); compile error

### ISSUE THREAD

**Issue by dreamer-design** [surge-synthesizer/clap-saw-demo#45]
the library vstgui doesn't compile on fedora 40-41.

error:
clap-saw-demo-editor.cpp
   21 |                 other.invoke (false);

issue:
https://github.com/steinbergmedia/vstgui/issues/324

fix:
clap-saw-demo/libs/vstgui/vstgui/lib/finally.h
line 21:
other.invoke = false;

i also had to install quite a few dependencies manually.
all the X11, xcb, xkb, cairo, pangocairo and sqlite.
not familiar with cmake though.

**Comment by baconpaul** [comment]
Ahh we probably have to upgrade the submodule to get the latest yeah.

As to the other dependencies, yes, cmake doesn't install them. There's a variety of approaches to this but the one we've taken in this particular project is list them in the workflow for ubuntu where we do CI builds and let folks figure them out on other linux-originated systems. If you'd like to share how you made it build on fedora from a package perspective either in the README or the doc I would happily merge that. 

Let me try a PR with latest vstgui.

**Comment by baconpaul** [comment]
OK if #46 passes CI I'll merge it and this will sweep the above change. When I do this issue will close.

Thanks!
